#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
PipelineScript_Photo_OpenRootDarktable.py
Author: Florian Dheer
Description: Import a photo project's root folder into Darktable (files
directly in it only - no subfolders such as _export) and show it in the
lighttable. Headless - no window of its own; problems are reported in a
message box.

`darktable <folder>` is not used: on Darktable 5.2.1 it crashes, and it only
opens a collection without importing anything. Instead Darktable is started
with a small Lua script (--luacmd) that imports the folder through
darktable.database.import and, once the import has finished, points the
lighttable collection at that folder's film roll. Recursive import is
switched off for this run with `--conf` (not saved to darktablerc).

Darktable allows one instance per library, so this cannot hand the folder to
an already-running Darktable.

Usage:
    PipelineScript_Photo_OpenRootDarktable.py <project_folder>
"""

import subprocess
import sys
from pathlib import Path
from typing import List

from shared_appdata import get_appdata_path
from shared_logging import get_logger, setup_logging as setup_shared_logging
from shared_message import show_message
from workstation_apps import App, resolve_exe_path

logger = get_logger("photo_open_root")

TITLE = "Open in Darktable"

# Files Darktable imports that a photo project's root can hold: RAW plus the
# usual picture formats (sidecars, videos and the like are skipped).
IMPORTABLE_EXTENSIONS = {
    ".cr2", ".cr3", ".nef", ".arw", ".raf", ".orf", ".rw2", ".dng", ".pef",
    ".srw", ".raw", ".3fr",
    ".jpg", ".jpeg", ".png", ".tif", ".tiff", ".heic", ".heif", ".webp",
    ".avif", ".jxl",
}

# Not on PATH after a normal install, so resolve_exe_path falls through to
# this folder and then to the registry uninstall entry.
DARKTABLE = App(
    name="darktable",
    exe="darktable",
    detect_paths=[r"%ProgramFiles%\darktable\bin"],
)

# Rewritten on every run, next to the rest of FastRack's per-user files.
LUA_SCRIPT_PATH = get_appdata_path() / "darktable_open_root.lua"

# `root` goes in a long-bracket string so no path character needs escaping.
LUA_TEMPLATE = """\
-- Generated by PipelineScript_Photo_OpenRootDarktable.py; overwritten on every run.
local dt = require 'darktable'
local root = [==[{root}]==]

local function norm(p)
  return (p:gsub('\\\\', '/'):gsub('/+$', ''):lower())
end

-- The import runs in the background and raises post-import-film for the
-- top-level film when it is done. Only react to this folder, and only once,
-- so a later manual import in the same session does not steal the collection.
local done = false
dt.register_event('fastrack-open-root', 'post-import-film', function(event, film)
  if done or norm(film.path) ~= norm(root) then return end
  done = true
  local ok, err = pcall(function()
    local rule = dt.gui.libs.collect.new_rule()
    rule.item = 'DT_COLLECTION_PROP_FILMROLL'
    rule.data = film.path
    dt.gui.libs.collect.filter({{rule}})
    dt.gui.current_view(dt.gui.views.lighttable)
  end)
  if not ok then dt.print_error('fastrack-open-root: ' .. tostring(err)) end
end)

dt.database.import(root)
"""


def _has_importable_files(folder: Path) -> bool:
    """True if `folder` directly contains at least one importable picture."""
    try:
        return any(
            e.is_file() and e.suffix.lower() in IMPORTABLE_EXTENSIONS
            for e in folder.iterdir()
        )
    except OSError as e:
        logger.warning(f"Could not list {folder}: {e}")
        return False


def _darktable_running() -> bool:
    """True if a Darktable process is running. Fails open (False) when the
    process list can't be read - Darktable then reports its own lock."""
    if sys.platform == "win32":
        cmd = ["tasklist", "/FI", "IMAGENAME eq darktable.exe", "/NH", "/FO", "CSV"]
    else:
        cmd = ["pgrep", "-x", "darktable"]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=10)
    except (OSError, subprocess.SubprocessError) as e:
        logger.warning(f"Could not check for a running Darktable: {e}")
        return False
    if sys.platform == "win32":
        return "darktable.exe" in result.stdout.lower()
    return result.returncode == 0


def write_lua_script(root: Path, script_path: Path = LUA_SCRIPT_PATH) -> Path:
    """Write the Lua import script for `root` to `script_path` and return it."""
    script_path.parent.mkdir(parents=True, exist_ok=True)
    root_lua = str(root).replace("\\", "/")
    script_path.write_text(LUA_TEMPLATE.format(root=root_lua), encoding="utf-8")
    return script_path


def build_command(exe: str, script_path: Path) -> List[str]:
    """Darktable command line that runs `script_path` on startup."""
    script_lua = str(script_path).replace("\\", "/")
    return [
        exe,
        "--conf", "ui_last/import_recursive=false",
        "--luacmd", f"dofile([==[{script_lua}]==])",
    ]


def main():
    setup_shared_logging("photo_open_root")

    if len(sys.argv) < 2:
        logger.error("Usage: PipelineScript_Photo_OpenRootDarktable.py <project_folder>")
        sys.exit(1)

    root = Path(sys.argv[1])
    if not root.is_dir():
        logger.error(f"Project folder not found: {root}")
        show_message(TITLE, f"Project folder not found:\n{root}")
        sys.exit(1)

    if not _has_importable_files(root):
        logger.info(f"No importable pictures directly in {root}")
        show_message(TITLE, f"There are no pictures directly in the project folder:\n{root}", error=False)
        return

    exe = resolve_exe_path(DARKTABLE)
    if not exe:
        logger.error("Darktable executable not found")
        show_message(
            TITLE,
            "Darktable was not found.\n\nInstall it from the Workstation Apps tab in Settings "
            "(or winget install darktable.darktable).",
        )
        sys.exit(1)

    if _darktable_running():
        logger.info("Darktable is already running - not launching a second instance")
        show_message(
            TITLE,
            "Darktable is already open. It only allows one window per library, so this "
            "can't add the folder to it.\n\nClose Darktable and click again.",
            error=False,
        )
        return

    try:
        command = build_command(exe, write_lua_script(root))
        subprocess.Popen(command)
        logger.info(f"Launched Darktable to import {root}: {command}")
    except OSError as e:
        logger.error(f"Failed to launch Darktable: {e}")
        show_message(TITLE, f"Could not start Darktable:\n{e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
